util/gl: link against OPENGL_gl_LIBRARY on waffle-less systems
Currently Windows builds statically link against piglitutil &
piglitutil_gl, with the opengl32.dll dependency present in the
executable link list.

As we move to a standalone dll(s) similar to linux, with follow-up
commits, building piglitutil_gl fails as it lacks OPENGL_gl_LIBRARY
required by the gl dispatch as shown below.

(piglit-dispatch-init.c.obj): In function `get_ext_proc_address':
piglit-dispatch-init.c:84: undefined reference to `__imp_wglGetProcAddress'

On Linux we were rather fortunate (apart from using waffle by default),
as the ld is smart enough to load libglut, which explicitly pulls libGL,
thus glXGetProcAddress{,ARB} ends up resolved.

Signed-off-by: Emil Velikov <emil.l.velikov@gmail.com>