util: Define usleep for MSVC only.
MinGW has usleep.

Fixes MinGW build error introduced in previous commit.

piglit-util.h:76:30: error: expected declaration specifiers or '...' before '(' token
 #define usleep(__usec) Sleep(((__usec) + 999)/1000)
                              ^

Signed-off-by: Vinson Lee <vlee@freedesktop.org>