ext_image_dma_buf_import: Include image_common.h from sample_common.c
Fixes build failure against current Mesa Git master:

.../sample_common.c.o: In function `sample_and_destroy_img':
.../sample_common.c:107: undefined reference to `eglDestroyImageKHR'
.../sample_common.c.o: In function `sample_buffer':
.../sample_common.c:128: undefined reference to `eglCreateImageKHR'
collect2: error: ld returned 1 exit status

The functions are/should be retrieved at runtime via eglGetProcAddress.
Latest Mesa master enforces this, by no longer providing the symbols
statically. This issue originates with the unfortunate removal of
image_common.h with

commit ec8feb99a81434db6bca66abac07a7822935ed8e
Author: Chad Versace <chad.versace@linux.intel.com>
Date:   Fri Sep 20 11:16:10 2013 -0700

    ext_image_dma_buf_import: Cleanup up #includes

Bugzilla: https://bugs.freedesktop.org/show_bug.cgi?id=90458
Signed-off-by: Michel Dänzer <michel.daenzer@amd.com>
[Emil Velikov: Add some context in the commit message.]
Reviewed-by: Emil Velikov <emil.l.velikov@gmail.com>